// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luxsjpodtupeazrxnbdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1eHNqcG9kdHVwZWF6cnhuYmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NDY4MjMsImV4cCI6MjA1MjQyMjgyM30.w7j1YkWhPEnvpQOiZ-ANTxed5TBDAeFu9iLFx_VYXc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);